apiVersion: v1
kind: Service
metadata:
  name: service-greeting-george-service 
spec:
  ports:
  - port: 30005
    nodePort: 30005
    targetPort: 8080 
  selector:
    app: service-greeting-george
  type: NodePort
